mode = "fastest"

[light_sources]
	water_sensitive_check = false
	block_entities = false
	entities = true
	self = true
	tnt = "simple"
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				player = true
				allay = true
				area_effect_cloud = true
				armor_stand = true
				arrow = true
				axolotl = true
				bat = true
				bee = true
				blaze = true
				block_display = true
				boat = true
				camel = true
				cat = true
				cave_spider = true
				chest_boat = true
				chest_minecart = true
				chicken = true
				cod = true
				command_block_minecart = true
				cow = true
				creeper = true
				dolphin = true
				donkey = true
				dragon_fireball = true
				drowned = true
				egg = true
				elder_guardian = true
				end_crystal = true
				ender_dragon = true
				ender_pearl = true
				enderman = true
				endermite = true
				evoker = true
				evoker_fangs = true
				experience_bottle = true
				experience_orb = true
				eye_of_ender = true
				falling_block = true
				firework_rocket = true
				fox = true
				frog = true
				furnace_minecart = true
				ghast = true
				giant = true
				glow_item_frame = true
				glow_squid = true
				goat = true
				guardian = true
				hoglin = true
				hopper_minecart = true
				horse = true
				husk = true
				illusioner = true
				interaction = true
				iron_golem = true
				item = true
				item_display = true
				item_frame = true
				fireball = true
				leash_knot = true
				lightning_bolt = true
				llama = true
				llama_spit = true
				magma_cube = true
				marker = true
				minecart = true
				mooshroom = true
				mule = true
				ocelot = true
				painting = true
				panda = true
				parrot = true
				phantom = true
				pig = true
				piglin = true
				piglin_brute = true
				pillager = true
				polar_bear = true
				potion = true
				pufferfish = true
				rabbit = true
				ravager = true
				salmon = true
				sheep = true
				shulker = true
				shulker_bullet = true
				silverfish = true
				skeleton = true
				skeleton_horse = true
				slime = true
				small_fireball = true
				sniffer = true
				snow_golem = true
				snowball = true
				spawner_minecart = true
				spectral_arrow = true
				spider = true
				squid = true
				stray = true
				strider = true
				tadpole = true
				text_display = true
				tnt = true
				tnt_minecart = true
				trader_llama = true
				trident = true
				tropical_fish = true
				turtle = true
				vex = true
				villager = true
				vindicator = true
				wandering_trader = true
				warden = true
				witch = true
				wither = true
				wither_skeleton = true
				wither_skull = true
				wolf = true
				zoglin = true
				zombie = true
				zombie_horse = true
				zombie_villager = true
				zombified_piglin = true
				fishing_bobber = true

			[light_sources.settings.entities.betternether]
				firefly = true
				hydrogen_jellyfish = true
				naga = true
				flying_pig = true
				jungle_skeleton = true
				skull = true
				naga_projectile = true

			[light_sources.settings.entities.bclib]
				chair = true

			[light_sources.settings.entities.betterend]
				dragonfly = true
				end_slime = true
				end_fish = true
				shadow_walker = true
				cubozoa = true
				silk_moth = true

			[light_sources.settings.entities.bosses_of_mass_destruction]
				lich = true
				blue_fireball = true
				comet = true
				soul_star = true
				charged_ender_pearl = true
				obsidilith = true
				gauntlet = true
				void_blossom = true
				spore_ball = true
				petal_blade = true

			[light_sources.settings.entities.creeperoverhaul]
				jungle_creeper = true
				bamboo_creeper = true
				desert_creeper = true
				badlands_creeper = true
				hills_creeper = true
				savannah_creeper = true
				mushroom_creeper = true
				swamp_creeper = true
				dripstone_creeper = true
				cave_creeper = true
				dark_oak_creeper = true
				spruce_creeper = true
				beach_creeper = true
				snowy_creeper = true
				ocean_creeper = true

			[light_sources.settings.entities.duckling]
				duck = true
				quackling = true
				duck_egg = true

			[light_sources.settings.entities.ecologics]
				coconut_crab = true
				boat = true
				chest_boat = true
				penguin = true
				squirrel = true

			[light_sources.settings.entities.endermanoverhaul]
				badlands_enderman = true
				cave_enderman = true
				crimson_forest_enderman = true
				dark_oak_enderman = true
				desert_enderman = true
				end_enderman = true
				end_islands_enderman = true
				flower_fields_enderman = true
				ice_spikes_enderman = true
				mushroom_fields_enderman = true
				nether_wastes_enderman = true
				coral_enderman = true
				savanna_enderman = true
				snowy_enderman = true
				soulsand_valley_enderman = true
				swamp_enderman = true
				warped_forest_enderman = true
				windswept_hills_enderman = true
				pet_enderman = true
				hammerhead_pet_enderman = true
				axolotl_pet_enderman = true
				scarab = true
				spirit = true
				ender_bullet = true
				corrupted_pearl = true
				soul_pearl = true
				ancient_pearl = true
				bubble_pearl = true
				summoner_pearl = true
				icy_pearl = true
				crimson_pearl = true
				warped_pearl = true

			[light_sources.settings.entities.farmersdelight]
				rotten_tomato = true

			[light_sources.settings.entities.graveyard]
				reaper = true
				acolyte = true
				corrupted_vindicator = true
				corrupted_pillager = true
				skeleton_creeper = true
				falling_corpse = true
				ghoul = true
				revenant = true
				wraith = true
				nightmare = true
				ghouling = true
				lich = true
				skull = true
				nameless_hanged = true

			[light_sources.settings.entities.illagerinvasion]
				provoker = true
				invoker = true
				necromancer = true
				basher = true
				sorcerer = true
				archivist = true
				inquisitor = true
				marauder = true
				alchemist = true
				firecaller = true
				surrendered = true
				invoker_fangs = true
				flying_magma = true
				skull_bolt = true
				hatchet = true

			[light_sources.settings.entities.minecells]
				leaping_zombie = true
				shocker = true
				grenadier = true
				disgusting_worm = true
				inquisitor = true
				kamikaze = true
				protector = true
				undead_archer = true
				shieldbearer = true
				mutated_bat = true
				sewers_tentacle = true
				rancid_rat = true
				runner = true
				scorpion = true
				buzzcutter = true
				sweeper = true
				conjunctivius = true
				concierge = true
				grenade = true
				big_grenade = true
				disgusting_worm_egg = true
				magic_orb = true
				scorpion_spit = true
				conjunctivius_projectile = true
				elevator = true
				cell = true
				tentacle_weapon = true
				spawner_rune = true
				conjunctivius_obelisk = true
				concierge_obelisk = true
				elite_obelisk = true
				shockwave_placer = true

			[light_sources.settings.entities.naturalist]
				duck_egg = true
				snail = true
				bear = true
				butterfly = true
				firefly = true
				snake = true
				coral_snake = true
				rattlesnake = true
				deer = true
				bluejay = true
				canary = true
				cardinal = true
				robin = true
				finch = true
				sparrow = true
				caterpillar = true
				rhino = true
				lion = true
				elephant = true
				zebra = true
				giraffe = true
				hippo = true
				vulture = true
				boar = true
				dragonfly = true
				catfish = true
				alligator = true
				bass = true
				lizard = true
				lizard_tail = true
				tortoise = true
				duck = true

			[light_sources.settings.entities.paladins]
				barrier = true
				battle_banner = true

			[light_sources.settings.entities.spell_engine]
				spell_projectile = true
				spell_area_effect = true

			[light_sources.settings.entities.dummmmmmy]
				target_dummy = true

			[light_sources.settings.entities.supplementaries]
				pearl_marker = true
				dispenser_minecart = true
				hat_stand = true
				red_merchant = true
				falling_urn = true
				falling_ash = true
				falling_sack = true
				brick_projectile = true
				bomb = true
				rope_arrow = true
				slingshot_projectile = true

		[light_sources.settings.block_entities]

			[light_sources.settings.block_entities.minecraft]
				furnace = true
				chest = true
				trapped_chest = true
				ender_chest = true
				jukebox = true
				dispenser = true
				dropper = true
				sign = true
				hanging_sign = true
				mob_spawner = true
				piston = true
				brewing_stand = true
				enchanting_table = true
				end_portal = true
				beacon = true
				skull = true
				daylight_detector = true
				hopper = true
				comparator = true
				banner = true
				structure_block = true
				end_gateway = true
				command_block = true
				shulker_box = true
				bed = true
				conduit = true
				barrel = true
				smoker = true
				blast_furnace = true
				lectern = true
				bell = true
				jigsaw = true
				campfire = true
				beehive = true
				sculk_sensor = true
				calibrated_sculk_sensor = true
				sculk_catalyst = true
				sculk_shrieker = true
				chiseled_bookshelf = true
				brushable_block = true
				decorated_pot = true

			[light_sources.settings.block_entities.bclib]
				chest = true
				barrel = true
				furnace = true

			[light_sources.settings.block_entities.betterend]
				end_stone_smelter = true
				pedestal = true
				eternal_pedestal = true
				infusion_pedestal = true
				hydrother_malvent = true

			[light_sources.settings.block_entities.betternether]
				forge = true
				furnace = true
				chest_of_drawers = true
				nether_brewing_stand = true

			[light_sources.settings.block_entities.bosses_of_mass_destruction]
				mob_ward = true
				monolith_block = true
				levitation_block = true
				void_blossom_block = true
				void_lily = true

			[light_sources.settings.block_entities.easyanvils]
				anvil = true

			[light_sources.settings.block_entities.easymagic]
				enchanting_table = true

			[light_sources.settings.block_entities.ecologics]
				sign = true
				hanging_sign = true
				pot = true

			[light_sources.settings.block_entities.farmersdelight]
				stove = true
				cooking_pot = true
				basket = true
				cutting_board = true
				skillet = true
				cabinet = true
				canvas_sign = true

			[light_sources.settings.block_entities.fwaystones]
				waystone = true

			[light_sources.settings.block_entities.graveyard]
				gravestone_block_entity = true
				urn_block_entity = true
				sarcophagus_block_entity = true
				brazier_block_entity = true
				ossuary_block_entity = true

			[light_sources.settings.block_entities.libraryferret]
				unbreakable_iron_beacon_entity = true
				unbreakable_gold_beacon_entity = true
				unbreakable_emerald_beacon_entity = true
				unbreakable_diamond_beacon_entity = true
				unbreakable_netherite_beacon_entity = true

			[light_sources.settings.block_entities.minecells]
				setup_block_entity = true
				biome_banner = true
				decorative_statue = true
				return_stone = true
				runic_vine_plant = true
				teleporter = true
				doorway = true
				barrier_controller = true
				spawner_rune = true
				rift = true
				arrow_sign = true

			[light_sources.settings.block_entities.spell_engine]
				spell_binding = true

			[light_sources.settings.block_entities.villagersplus]
				oceanographer_table_block_entity = true
				alchemist_table_block_entity = true
				occultist_table_block_entity = true
				horticulturist_table_block_entity = true

			[light_sources.settings.block_entities.yigd]
				grave_block_entity = true

			[light_sources.settings.block_entities.supplementaries]
				sign_post = true
				flag = true
				present = true
				trapped_present = true
				pedestal = true
				notice_board = true
				safe = true
				cage = true
				jar = true
				sack = true
				blackboard = true
				globe = true
				rope_knot = true
				bamboo_spikes = true
				goblet = true
				hourglass = true
				item_shelf = true
				doormat = true
				spring_launcher_arm = true
				speaker_block = true
				turn_table = true
				pulley_block = true
				bellows = true
				clock_block = true
				wind_vane = true
				faucet = true
				key_lockable_tile = true
				jar_boat = true
				structure_temp = true
				block_generator = true
				timber_frame = true
				flower_box = true
				statue = true
				book_pile = true
				urn = true
				bubble_block = true
				enderman_head = true

